---
- name: enable pacman parallel downloads
  lineinfile:
    path: /etc/pacman.conf
    insertafter: "^#ParallelDownloads"
    line: ParallelDownloads = 10
    regexp: "^ParallelDownloads"
  become: true

- name: enable multilib
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  become: true

- name: update cache
  pacman:
    update_cache: true
  become: true

- name: install
  kewlfft.aur.aur:
    name: yay-bin

- name: upgrade
  kewlfft.aur.aur:
    update_cache: true
    upgrade: true
