---
- name: disable auto sleep 
  dconf:
    key: "/org/cinnamon/settings-daemon/plugins/power/{{ item }}"
    value: "0"
  loop:
    - sleep-display-ac
    - sleep-display-battery
    - sleep-inactive-ac-timeout
    - sleep-inactive-battery-timeout
  become: true
  become_user: trojsten

- name: shutdown on lid close
  dconf:
    key: "/org/cinnamon/settings-daemon/plugins/power/{{ item }}"
    value: "'shutdown'"
  loop:
    - lid-close-battery-action
    - lid-close-ac-action
  become: true
  become_user: trojsten

- name: disable screensaver
  dconf:
    key: "/org/cinnamon/desktop/screensaver/{{ item }}"
    value: "false"
  loop:
    - idle-activation-enabled
    - lock-enabled
  become: true
  become_user: trojsten

- name: disable idle timeout
  dconf:
    key: "/org/cinnamon/desktop/session/idle-delay"
    value: "uint32 0"
  become: true
  become_user: trojsten

- name: poweroff on lid close
  become: true
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleLidSwitch=poweroff"
    regex: "^HandleLidSwitch="
    insertafter: "^#HandleLidSwitch="

- name: poweroff on lid close (ac)
  become: true
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleLidSwitchExternalPower=poweroff"
    regex: "^HandleLidSwitchExternalPower="
    insertafter: "^#HandleLidSwitchExternalPower="
