---
- name: install mint themes and fonts
  kewlfft.aur.aur:
    state: present
    name:
      - mint-themes
      - mint-y-icons

- name: configure theme
  dconf:
    key: "/org/cinnamon/theme/name"
    value: "'Mint-Y-Dark'"
  become: true
  become_user: trojsten

- name: configure cursor theme
  dconf:
    key: "/org/cinnamon/desktop/interface/cursor-theme"
    value: "'Adwaita'"
  become: true
  become_user: trojsten

- name: configure GTK theme
  dconf:
    key: "/org/cinnamon/desktop/interface/gtk-theme"
    value: "'Mint-Y-Dark'"
  become: true
  become_user: trojsten

- name: configure icon theme
  dconf:
    key: "/org/cinnamon/desktop/interface/icon-theme"
    value: "'Mint-Y-Dark'"
  become: true
  become_user: trojsten

- name: copy background
  copy:
    src: bg.png
    dest: /usr/share/backgrounds/trojsten.png
  become: true

- name: configure background
  dconf:
    key: "/org/cinnamon/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/trojsten.png'"
  become: true
  become_user: trojsten

- name: add nopasswdlogin group
  ansible.builtin.group:
      name: nopasswdlogin
      state: present
  become: true

- name: add trojsten to nopasswdlogin
  user:
    name: trojsten
    groups: nopasswdlogin
    append: yes
  become: true

- name: enable nopasswdlogin in lightdm
  ansible.builtin.lineinfile:
    path: /etc/pam.d/lightdm
    insertafter: '^#%PAM'
    line: 'auth sufficient pam_succeed_if.so user ingroup nopasswdlogin'
  become: true
