#!/usr/bin/env bash

if grep "subvol=@ " /proc/cmdline -q; then
	for i in {1..5}; do
	   echo -e "\033[0;31m * This Agent is not running inside a sandbox. Not starting display manager.\033[0m"
	done
    exit 1
else
	usermod -L management
fi
