#!/usr/bin/env bash
set -euo pipefail

if [ -d /.sandbox ]; then
	echo "Cleaning sandbox..."
    rm -rf /.sandbox
    btrfs subvolume snapshot / /.sandbox
    echo "Sandbox cleaned. Rebooting in 15 seconds."
    sleep 15
    reboot
else
	echo -e "\033[0;31mThis Agent is running inside a sandbox, ignoring.\033[0m"
fi
