---
- name: install common programs
  kewlfft.aur.aur:
    name:
      - git
      - vscodium
      - gedit
      - docker
      - docker-compose

- name: add user to docker group
  ansible.builtin.user:
    name: trojsten
    groups: docker
    append: true
  become: true

- name: enable docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
  become: true

- name: configure gedit theme
  dconf:
    key: "/org/gnome/gedit/preferences/editor/scheme"
    value: "'oblivion'"
  become: true
  become_user: trojsten

- import_tasks: python.yml
  tags: coding-python

- import_tasks: r.yml
  tags: coding-r

- import_tasks: cpp.yml
  tags: coding-cpp

- import_tasks: java.yml
  tags: coding-java

- import_tasks: js.yml
  tags: coding-js

- import_tasks: arduino.yml
  tags: coding-arduino
