---
- name: copy ssh key
  ansible.posix.authorized_key:
    user: management
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMX73gPFV3zp1vmx84fDuRGGKqV1tur5X/OMSiv8UzgD"

- name: allow the management user to use sudo without password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-nopasswd-management
    line: 'management ALL=(ALL) NOPASSWD: ALL'
    create: true
    validate: 'visudo -cf %s'

- name: copy snapshot utils to root home
  become: true
  ansible.builtin.copy:
    src: ent-snapshot
    dest: /root

- name: set hostname
  become: true
  hostname:
    name: "{{ ent_name }}"
