- name: install wireguard
  kewlfft.aur.aur:
    name:
      - wireguard-tools
  become: true

- name: create /etc/wireguard directory
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: true

- name: generate wireguard private key (if missing)
  ansible.builtin.shell: wg genkey > /etc/wireguard/{{ wg_interface }}.key
  args:
    creates: "/etc/wireguard/{{ wg_interface }}.key"
  become: true

- name: generate wireguard public key (if missing)
  ansible.builtin.shell: |
    cat /etc/wireguard/{{ wg_interface }}.key | wg pubkey > /etc/wireguard/{{ wg_interface }}.pub
  args:
    creates: "/etc/wireguard/{{ wg_interface }}.pub"
  become: true

- name: slurp private key from remote
  slurp:
    src: "/etc/wireguard/{{ wg_interface }}.key"
  register: slurped_wg_key
  become: true

- name: set private key content fact
  set_fact:
    wg_private_key_content: "{{ slurped_wg_key.content | b64decode }}"

- name: render WireGuard config
  template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wg_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: disallow network manager from managing wireguard connection
  copy:
    dest: "/etc/NetworkManager/conf.d/10-do-not-manage-trojsten-wireguard.conf"
    content: |
      [keyfile]
      unmanaged-devices=interface-name:trojsten
  become: true

- name: enable and start wireguard tunnel
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    enabled: yes
    state: started
  become: true
  ignore_errors: true
